on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:
    name: Build and test
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Run API Tests
        id: run-newman
        uses: berkaykirmizioglu/weather_newman@master
        with:
          collection: weatherbit_API.postman_collection.json
          environment: weatherbit_API_globals.json
          reporters: cli
      - name: Output summary to console
        run: echo ${{ steps.run-newman.outputs.summary }}
